CREATE DATABASE IF NOT EXISTS csa_library;
USE csa_library;

CREATE TABLE IF NOT EXISTS library_books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    author VARCHAR(120) NOT NULL,
    publisher VARCHAR(120) NOT NULL,
    published_year SMALLINT NOT NULL,
    isbn VARCHAR(30) NOT NULL UNIQUE,
    quantity INT NOT NULL DEFAULT 1,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
